[project]
org-name= "wso2"
version= "0.4.1"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ftp"]
repository= "https://github.com/wso2-ballerina/module-ftp"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    module = "utils/ftp-utils"
    path = "../ftp-utils/target/ftp-utils-module-0.4.1.jar"
    artifactId = "wso2-ftp"
    version = "0.4.1"
    groupId = "org.wso2.ei"
