[project]
org-name= "ballerina"
version= "0.5.1"
license= ["Apache-2.0"]
authors= ["Ballerina"]
keywords= ["ftp"]
repository= "https://github.com/ballerina-platform/module-ftp"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    module = "utils/ftp-utils"
    path = "../ftp-utils/target/ftp-utils-module-0.5.1.jar"
    artifactId = "wso2-ftp"
    version = "0.5.1"
    groupId = "org.wso2.ei"
