[package]
org = "ballerina"
name = "ftp"
version = "@toml.version@"
[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "runtime"
version = "@stdlib.runtime.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "task"
version = "@stdlib.task.version@"

[[platform.java11.dependency]]
path = "./lib/commons-vfs2-2.6.0.jar"
groupId = "org.apache.commons"
artifactId = "commons-vfs2"
version = "2.6.0"


[[platform.java11.dependency]]
path = "./lib/commons-net-3.6.jar"
groupId = "commons-net"
artifactId = "commons-net"
version = "3.6"


[[platform.java11.dependency]]
path = "./lib/testng-6.14.3.jar"
groupId = "org.testng"
artifactId = "testng"
version = "6.14.3"


[[platform.java11.dependency]]
path = "./lib/MockFtpServer-2.7.1.jar"
groupId = "org.mockftpserver"
artifactId = "MockFtpServer"
version = "2.7.1"


[[platform.java11.dependency]]
path = "./lib/org.wso2.transport.remote-file-system-6.0.57.jar"
groupId = "org.wso2.transport.file"
artifactId = "org.wso2.transport.remote-file-system"
version = "6.0.57"


[[platform.java11.dependency]]
path = "../ftp-native/build/libs/ftp-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "ftp"
version = "@project.version@"


[[platform.java11.dependency]]
path = "../ftp-test-utils/build/libs/ftp-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.ftp"
scope = "testOnly"
artifactId = "ftp"
version = "@project.version@"
