name: Deployment

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -  run: mvn clean install -pl !ftp
    -  run: cd ftp
    - name: Ballerina Build
      uses: ballerina-platform/ballerina-action/@master
      with:
        args:
          build -a -c --sourceroot ftp
      env:
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
    - name: Ballerina Push
      uses: ballerina-platform/ballerina-action/@master
      with:
        args: 
          push -a
      env:
        WORKING_DIR: ./ftp
        BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}

